### ISSUE TITLE
Symbolic panel icon

### ISSUE THREAD

**Issue by zagortenay333** [lestcape/Color-Chooser#2]
Any chance of getting a symbolic icon up there? Most icon themes already provide a symbolic color picker icon.

**Comment by lestcape** [comment]
Yes, but i consider also instead of an icon display the last selected color. Will be more useful than a non related icon, i also can show the color in an string format in the panel in a text Entry or a label. What you consider the best here? My target is not this applet, this is an utility to do more things. I have a plan to migrate the cinnamon settings to be displayed inside an applet popupmenu.

**Comment by zagortenay333** [comment]
Personally I'd prefer an icon. Not sure of what use it would to have the color displayed on the panel. Maybe as an option?

**Comment by lestcape** [comment]
Added an option to show symbolic icon or full -color: https://github.com/lestcape/Color-Chooser/commit/bae95d7047f04d10a82940890b1f036fc3ed95c0
